# This is a basic workflow to help you get started with Actions

name: Build and publish images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ devops ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  base_version: 0.0
  image_repo_url: ghcr.io/Dev0psTools/kubectl

jobs:
  build:
    name: Build version
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        kubectl_version: [ '1.20.14','1.21.8','1.22.5','1.23.1' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set assembly version
        run: |
          kubectl_version=${{ matrix.kubectl_version }}
          major_version=${kubectl_version%.*}
          echo $major_version
