# This is a basic workflow to help you get started with Actions

name: Build and publish images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ devops ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  base_version: 0.0
  image_repo_url: ghcr.io/dev0pstools/kubectl

jobs:
  build:
    name: Build version
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        kubectl_version: [ '1.20.14','1.21.8','1.22.5','1.23.1' ]
    steps:
      - uses: actions/checkout@v2

      - name: Set assembly version
        run: |
          kubectl_version=${{ matrix.kubectl_version }}
          major_version=${kubectl_version%.*}
          assembly_version="${{ env.base_version }}.${GITHUB_RUN_NUMBER}"
          echo "KUBECTL_VERSION=$kubectl_version" >> $GITHUB_ENV
          echo "KUBECTL_MAJOR_VERSION=$major_version" >> $GITHUB_ENV
          echo "ASSEMBLY_VERSION=$assembly_version" >> $GITHUB_ENV

      - name: Build docker image
        run: |
          docker build -t ${{ env.image_repo_url }}:${KUBECTL_VERSION} \
            --build-arg assembly_version=${ASSEMBLY_VERSION} \
            --build-arg kubectl_version=${KUBECTL_VERSION} .
